---
development:
  cloud_name: bmmerce
  api_key: '671386158788172'
  api_secret: tCl7YIWXe0d5nqeyWf4wxSexIYM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: bmmerce
  api_key: '671386158788172'
  api_secret: tCl7YIWXe0d5nqeyWf4wxSexIYM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: bmmerce
  api_key: '671386158788172'
  api_secret: tCl7YIWXe0d5nqeyWf4wxSexIYM
  enhance_image_tag: true
  static_image_support: false